[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.15",
    "aiosignal==1.4.0",
    "attrs==25.3.0",
    "frozenlist==1.7.0",
    "idna==3.10",
    "multidict==6.6.4",
    "orjson==3.11.3",
    "propcache==0.3.2",
    "typing-extensions==4.15.0",
    "websockets==15.0.1",
    "yarl==1.20.1",
]
